# This is a basic workflow to help you get started with Actions

name: OSSIBOT Audit
inputs: 
  OSSIEBOT_ID:
    required: true
runs:
  using: composite
  steps: 
        # Install OssiBOT
    - name: install ossie bot client
      run: pip3 install ossie
      shell: bash

    - name: Check depalert
      run: |
        (ls ${{ github.workspace }}/.depalert &> /dev/null && echo "deplert exists") || echo "No depalert"
      shell: bash
      
#     # Audit the Repository
    - name: Audit project dependencies
      run: ossie audit --id ${{ inputs.OSSIEBOT_ID }} --project ${{ github.workspace }}
      shell: bash
