# This is a basic workflow to help you get started with Actions

name: OSSIBOT Audit
inputs: 
  OSSIEBOT_ID:
    required: true
runs:
  using: composite
  steps: 
        # Install OssiBOT
    - name: install ossie bot client
      run: pip3 install git+https://github.com/sbmthakur/ossie-pypi.git@main
      shell: bash
      
#     # Audit the Repository
    - name: Audit project dependencies
      run: |
        # Enable alias
        shopt -s expand_aliases
        
        # Audit with depalert
        alias run_depalert='ossie audit --id ${{ inputs.OSSIEBOT_ID }} --depalert true'
        
        # Audit without depalert
        alias run_ossie='ossie audit --id ${{ inputs.OSSIEBOT_ID }} --project ${{ github.workspace }}'
        
        # Call depalert alias if it's present
        (ls ${{ github.workspace }}/.depalert &> /dev/null && run_depalert) || run_ossie
      shell: bash
